#
# Static assets uploaded to the assets S3 bucket.
#
# Consumers:
#   cache builder EC2     models.yaml, models.json, scripts
#   internal tooling      models.json (routing/dispatch reference)
#
# Source files:
#   assets/models.yaml                   committed, hand-maintained
#   assets/models.json                   generated by: make generate-models (tfvars + json)
#                                        committed; internal catalogue with infra fields
#   package/src/models/cache_model.py    per-model HuggingFace downloader
#
# Run `make generate-models` and `make generate-catalogue` after changing
# models.yaml, then commit all four generated files before running apply.
#

locals {
  models_yaml_raw             = file("${path.module}/../../assets/models.yaml")
  models_json_raw             = file("${path.module}/../../assets/models.json")
}

resource "aws_s3_object" "models_yaml" {
  bucket       = aws_s3_bucket.data.id
  key          = "models.yaml"
  content      = local.models_yaml_raw
  content_type = "application/x-yaml"
  etag         = md5(local.models_yaml_raw)

  tags = var.project_tags
}

# Internal catalogue -- consumed by the cache builder and internal tooling.
# Contains infrastructure fields (queue URLs, task definitions, etc).
# Not served publicly.
resource "aws_s3_object" "models_json" {
  bucket       = aws_s3_bucket.data.id
  key          = "models.json"
  content      = local.models_json_raw
  content_type = "application/json"
  etag         = md5(local.models_json_raw)

  tags = var.project_tags
}

output "models_yaml_s3_key" {
  description = "S3 key for models.yaml"
  value       = aws_s3_object.models_yaml.key
}

output "models_json_s3_key" {
  description = "S3 key for models.json (internal; consumed by cache builder)"
  value       = aws_s3_object.models_json.key
}
