ARG BASE_IMAGE=python:3.12-slim
FROM $BASE_IMAGE AS base_image

ENV HF_HUB_DISABLE_PROGRESS_BARS=1
ENV HF_HUB_DISABLE_TELEMETRY=1
ENV HF_HOME=/tmp
ENV HF_HUB_CACHE=/models
ENV HF_HUB_OFFLINE=1

ENV MODELNAME="UNSET"
ENV LOAD_IN_4BIT=0
ENV REMOTE_CODE=0
ENV USE_FAST=0

# we need git for the absolute latest version of https://github.com/huggingface/diffusers.git
#RUN apt-get update && apt-get install -y git

# install `lame` for the tts and other audio outputs
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

# build the torch/hf/env
ARG TORCH_REQS=pytorch-cpu.requirements.txt
COPY ./package/src/models/environment/$TORCH_REQS /tmp/requirements.txt
RUN pip install --no-cache-dir --break-system-packages  -r /tmp/requirements.txt

COPY ./package/src/models/environment/huggingface.requirements.txt  /tmp/requirements.txt
RUN pip install --no-cache-dir --break-system-packages -r /tmp/requirements.txt

COPY ./package/src/models/environment/diffusers.requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --break-system-packages -r /tmp/requirements.txt

COPY ./package/src/models/environment/misc.requirements.txt  /tmp/requirements.txt
RUN pip install --no-cache-dir --break-system-packages -r /tmp/requirements.txt

# get package deps
COPY ./requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --break-system-packages -r /tmp/requirements.txt

# add the test script
ARG GPU_ENABLED=0
ENV GPU_ENABLED=$GPU_ENABLED
#COPY ./package/src/models/environment/container-info.py
#RUN python3 ./container-info.py

# build the actual image
FROM base_image

ARG GIT_TAG=unknown
ENV BUILD_VERSION=${GIT_TAG}

# copy code into container
WORKDIR /app
COPY ./package/src .

CMD ["python3", "-c", "import logging; logging.warning('container booted'); import time; time.sleep(30)"]
