ARG BASE_IMAGE=nvidia/cuda:13.1.2-cudnn-runtime-ubuntu24.04
FROM $BASE_IMAGE AS base_image

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
software-properties-common build-essential wget curl git ca-certificates && \
add-apt-repository ppa:deadsnakes/ppa && apt-get update && \
apt-get install -y --no-install-recommends python3 python3-dev python3-pip && \
apt-get clean && rm -rf /var/lib/apt/lists/*
