"""
Generate assets/models.tfvars from assets/models.yaml.

Usage:
    python3 scripts/generate_models_tfvars.py

Reads assets/models.yaml relative to the project root (one level above this script).
Writes assets/models.tfvars. The output file is consumed by Terraform layers 02 and 03
via -var-file and should not be committed to version control.

Requirements:
    pip install pyyaml
"""

import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("error: pyyaml is required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


VALID_TYPES = {
    "text-embedding",
    "instruct",
    "tts",
    "depth",
    "image-embedding",
    "img2txt",
    "txt2img",
    "img2mask",
    "txt2audio",
    "img2mesh",
}

REQUIRED_FIELDS = {"name", "type", "handler", "input", "output"}


def make_key(name: str) -> str:
    """
    Derive a deterministic Terraform map key from a HuggingFace model name.

    Rules:
    - lowercase
    - forward slash (org separator) becomes hyphen
    - dots removed
    - any remaining non-alphanumeric-hyphen characters removed
    - consecutive hyphens collapsed
    """
    key = name.lower()
    key = key.replace("/", "-")
    key = re.sub(r"\.", "", key)
    key = re.sub(r"[^a-z0-9-]", "-", key)
    key = re.sub(r"-+", "-", key)
    return key.strip("-")


def make_env_vars(model: dict) -> dict:
    """
    Construct the environment_variables map from model fields.
    All values must be strings -- Terraform map(string) requires this.
    """
    env = {
        "MODELNAME":    model["name"],
        "MODEL_TYPE":   model["type"],
        "MODEL_INPUT":  model["input"],
        "MODEL_OUTPUT": model["output"],
    }

    if model["type"] == "instruct":
        env["LOW_CPU_MEM_USAGE"] = "1"

    if "langcode" in model:
        env["MODEL_LANGCODE"] = model["langcode"]

    if "log_level" in model:
        env["LOG_LEVEL"] = model["log_level"].upper()

    for k, v in model.get("extra_env", {}).items():
        env[k] = str(v)

    return env


def validate(models: list) -> list:
    errors = []
    seen_names = set()

    for i, m in enumerate(models):
        label = f"models[{i}] ({m.get('name', '<unnamed>')})"

        for field in REQUIRED_FIELDS:
            if field not in m:
                errors.append(f"{label}: missing required field '{field}'")

        name = m.get("name", "")
        if name:
            if name in seen_names:
                errors.append(f"{label}: duplicate model name '{name}'")
            seen_names.add(name)

        model_type = m.get("type", "")
        if model_type and model_type not in VALID_TYPES:
            errors.append(
                f"{label}: unknown type '{model_type}'. "
                f"Valid types: {sorted(VALID_TYPES)}"
            )

    return errors


def hcl_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_tfvars(models: list) -> str:
    lines = [
        "# Generated by scripts/generate_models_tfvars.py",
        "# Source: assets/models.yaml",
        "# Do not edit manually.",
        "",
        "models = {",
    ]

    for model in models:
        key = make_key(model["name"])
        env = make_env_vars(model)
        memory_size = int(model.get("memory_size", 9216))
        timeout     = int(model.get("timeout", 300))
        image       = model.get("image", "environment")
        vector_size = int(model.get("vector_size", 0))

        lines.append(f"  {hcl_str(key)} = {{")
        lines.append(f"    image       = {hcl_str(image)}")
        lines.append(f"    handler     = {hcl_str(model['handler'])}")
        lines.append(f"    memory_size = {memory_size}")
        lines.append(f"    timeout     = {timeout}")
        lines.append(f"    vector_size = {vector_size}")
        lines.append(f"    environment_variables = {{")
        for k, v in env.items():
            lines.append(f"      {hcl_str(k)} = {hcl_str(v)}")
        lines.append( "    }")
        lines.append( "  },")
        lines.append("")

    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    root      = Path(__file__).resolve().parent.parent
    yaml_path = root / "assets" / "models.yaml"
    out_path  = root / "assets" / "models.tfvars"

    if not yaml_path.exists():
        print(f"error: {yaml_path} not found", file=sys.stderr)
        sys.exit(1)

    with yaml_path.open() as fh:
        config = yaml.safe_load(fh)

    models = config.get("models", [])
    if not models:
        print("error: no models found in models.yaml", file=sys.stderr)
        sys.exit(1)

    errors = validate(models)
    if errors:
        for e in errors:
            print(f"error: {e}", file=sys.stderr)
        sys.exit(1)

    content = render_tfvars(models)
    out_path.write_text(content)
    print(f"wrote {len(models)} models to {out_path}")


if __name__ == "__main__":
    main()
